# Default values for WORDS_COUNTER_BATCH.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

S3objectCron:
  enabled: true
  image:
    repository: localhost:32000/s3-objects-words-count-daily-check
    tag: latest
    pullPolicy: IfNotPresent
    pullSecret: docker-private-creds

  schedule:
    cron: 0 0 * * *

  Bucket:
    name: samh-s3-bucket

  env:
    secretKeyRefName: aws-creds
    region: us-east-1

  restartPolicy: OnFailure


cleanup:
  enabled: true
  image:
    repository: samer1984/kubectl-fast-deploy-alpine
    tag: latest
    pullPolicy: IfNotPresent

  schedule:
    cron: 0 1 * * *
    successfulJobsHistoryLimit: 0
    failedJobsHistoryLimit: 0

  cleanCommand: kubectl delete jobs --field-selector status.successful=1

  Volumes:
    HostPath: /home/sam/.kube-conf-to-mount

  restartPolicy: OnFailure
