{
 "title": "RDS Dashboard",
 "time": { "from": "2020-05-23T01:57:15.033Z", "to": "2020-06-06T01:57:15.033Z" },
 "panels": [
  {
   "title": "Words Count Table",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Insertion_date AS \"time\",\n  ObjectPath AS metric,\n  AmountOfWords\nFROM WordsCount\nWHERE\n  $__timeFilter(Insertion_date)\nORDER BY Insertion_date"
    }
   ]
  },
  {
   "title": "Words Count per file",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Insertion_date AS \"time\",\n  AmountOfWords\nFROM WordsCount\nWHERE\n  $__timeFilter(Insertion_date)\nORDER BY Insertion_date"
    }
   ]
  },
  {
   "title": "Files-S3-objects",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Insertion_date AS \"time\",\n  ObjectPath AS metric,\n  AmountOfWords\nFROM WordsCount\nWHERE\n  $__timeFilter(Insertion_date)\nORDER BY Insertion_date"
    }
   ]
  },
  {
   "title": "Amount of Lines number",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  Insertion_date AS \"time\",\n  AmountOfLines\nFROM LinesCount\nWHERE\n  $__timeFilter(Insertion_date)\nORDER BY Insertion_date"
    }
   ]
  }
 ]
}